---
name: Scan Devcontainer Image

on:
  push:
    branches:
      - main
  pull_request: null

permissions: {}

jobs:
  scan-devcontainer:
    name: Scan Devcontainer Image

    permissions:
      actions: read
      security-events: write

    uses: Vianpyro/Template/.github/workflows/docker-image-verification.yml@main
    with:
      image_name: devcontainer
      dockerfile_path: ./Dockerfile
      context: .devcontainer
